name             'rax-chef-assesment'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs wordpress on LAMP stack'
long_description 'Installs wordpress on LAMP stack'
version          '0.1.0'

depends          'apt'
depends          'apache2'
depends          'php'
depends          'php-fpm'
depends          'mysql'
depends          'phpmyadmin'
depends          'wordpress'
depends          'varnish'
